### ISSUE TITLE
Java libraries not detected

### ISSUE THREAD

**Issue by poqudrof** [jashkenas/ruby-processing#110]
Hello, 

I installed the latest version from ruby gems, and the libraries do not load.
I spend some time investigating here are solutions : 

add this line to  ~/.rp5rc 

``` json
  "sketchbook_path": "/home/jiii/sketchbook",
```

I needed to look into the code to find out this solution. So the other solution : 

in `library_loader.rb`
``` ruby 
      lines = File.readlines(preferences_paths.first)
      regex1 = /^sketchbook\.path=(.+)/           # processing-2.0
#      regex2 = /^sketchbook\.path\.three=(.+)/    # processing-3.0
      matched_lines = lines.grep(regex1) { $1 } unless $1 == ''
#      matched_lines = lines.grep(regex2) { $1 } unless $1 == ''

```
"Just comment out" the processing3 compatibility. I am not so good at ruby for now, and I saw it is in active development. 
Maybe you should decide to use the processing preferences for long-term, but for now the rp5rc solution is easy to set up for everyone :] 

Cheers, 

Jeremy.

**Comment by monkstone** [comment]
Thanks for opening issue, if like me you have both processing-2.2.1 and processing-3.0a5 then current version works. However I  think prefer the config solution, I have just done another pre-release of [JRubyArt][] the development version, which can be used without a vanilla processing install (so uses the config route).
 [JRubyArt]:https://github.com/ruby-processing/JRubyArt

**Comment by monkstone** [comment]
@poqudrof should be fixed in latest release?
