### ISSUE TITLE
Argument is missing for "-J-cp" option.

### ISSUE THREAD

**Issue by chwongris** [jashkenas/ruby-processing#122]
Hi, I'm having an issue running sketches.  Keep getting a "Argument is missing for "-J-cp" option." error.

Running Mac OSX 10.10.4, Processing 2.2.1

ruby
$ rvm current
jruby-1.7.12

java
$ java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

jruby
$ jruby -v
jruby 1.7.12 (1.9.3p392) 2014-04-15 643e292 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26 +indy [darwin-x86_64]

$ rp5 run samples/contributed/jwishy.rb
Argument is missing for "-J-cp" option.

$ rp5 run samples/contributed/jwishy.rb  --nojruby
NameError: PApplet not found in packages processing.core; last error: cannot load Java class processing.core.PApplet
     const_missing at file:/Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby/jruby-complete.jar!/jruby/java/core_ext/module.rb:42
        Processing at /Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby-processing/app.rb:36
            (root) at /Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby-processing/app.rb:11
           require at org/jruby/RubyKernel.java:1040
            (root) at /Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at /Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
  require_relative at file:/Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby/jruby-complete.jar!/jruby/kernel19/kernel.rb:24
           require at org/jruby/RubyKernel.java:1040
            (root) at /Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby-processing/runners/base.rb:7
            (root) at /Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
            (root) at /Users/chriswong/.rvm/gems/jruby-1.7.12/gems/ruby-processing-2.6.13/lib/ruby-processing/runners/run.rb:4

.rp5rc file
{
  "JRUBY": true,
  "PROCESSING_ROOT": "/Applications/Processing.app/Contents/Resources/Java",
  "X_OFF": 144,
  "Y_OFF": 90
}

Thanks!

**Comment by monkstone** [comment]
Sorry about this issue, it came about because of my attempt to make ruby-processing compatible with jruby-9.0.0.0-rc2, see CHANGELOG. The compatibility problem went away with release of jruby-9.0.0.0 (the jruby team reversed decision about default class loader, and I also got them to fix a bug). The current unreleased version (ruby-processing-2.6.14) should not have the problem, as I have reversed those changes. I was delaying issuing the release for an expected jruby-1.7.22 release.  Please use ruby-processing-2.6.11, (or build version 2.6.14) in the meantime.

**Comment by chwongris** [comment]
Thanks for the quick response.  Had to downgrade to 2.6.10 to get rid of the error.  Also looks like the file path for the PROCESSING_ROOT now needs to be "/Applications/Processing.app/Contents/Java" to get it to run.

Thanks again.
