### ISSUE TITLE
Faster startup time with Drip

### ISSUE THREAD

**Issue by fedegl** [jashkenas/ruby-processing#82]
I have a daemon that runs processing sketches, so I wanted to integrate Drip in order to reduce the JVM startup time each time a new rp5 command is run.

I have tried installing it with this guide: https://gist.github.com/rjackson/4582914

The first time I run it it takes a while to start but it runs correctly.

The second time I run it, I get no output from the console. Then If I kill the drip daemon and run it again it runs, but it fails again the second time.

I am guessing that this most probably is a drip issue, but just wondering if you have tried using it in the past with any success.

Thanks.

**Comment by monkstone** [comment]
@fedgl @emilsoman
Certainly when using jruby-9000 the fastest start-up time for jruby is using the --dev flag. This is best appreciated with [JRubyArt][] where many sketches can be directly started with jruby.
[JRubyArt]:https://github.com/ruby-processing/JRubyArt

**Comment by monkstone** [comment]
There doesn't seem to be any progress here, so I am shelving issue for know.
